[controllables]
AutoExpMaxExpMS = 3000000                   
AutoExpMaxGain = 225                        
AutoExpTargetBrightness = 100               
BandWidth = "auto"                          
Exposure = 30000000  # in micro-seconds    # Default: 1000000 (1 second)
Flip = 0                                    # Default: 0
Gain = 100                                  # Default: 100
HardwareBin = 0                             # Default: 0
HighSpeedMode = 0                       
MonoBin = 0                                 
Offset = 5                                  
WB_B = 95  # DO NOT CHANGE WHITE BALANCE    # Default: 95
WB_R = 70                                   # Default: 70

[roi]                                       # Default is centered for a 20 MP 1" Sensor with a 2/3" Lens
start_x = 1374                              # Default: 1374
start_y = 464                               # Default: 464
width = 2744    # Must be a multiple of 8   # Default: 2744
height = 2744   # Must be a multiple of 2   # Default: 2744
binning = 1                                 # Default: 1 
imageType = "RGB24"                         # Default: "RGB24"

[paths]
Camera_Images_Collection="/Data/camera_images/" 
Camera_Info_Folder="/Data/image_info_files/"
Sensor_Data_Folder="/Data/sensor_files/"
GDrive_Folder_ID=0
Token_Path=0
Credits_Path=0

[formats]
Data_Folder         ="%Y_%m_%d_Data"
Image_Name_Format   ="%Y_%m_%d_exp"
Image_Extension     =".png"
Image_Folder_Format ="%Y_%m_%d_Images"
Camera_Info_Format  ="%Y_%m_%d_Cam_Info"
Sensor_Data_Format  ="%Y_%m_%d_Sensor_Data"

[passkeys]
