[controllables]
AutoExpMaxExpMS = 3000000
AutoExpMaxGain = 225
AutoExpTargetBrightness = 100
BandWidth = "auto"
Exposure = 2000000
Flip = 0
Gain = "auto"
HardwareBin = 0
HighSpeedMode = 0
MonoBin = 0
Offset = 5
WB_B = 95
WB_R = 70

[roi]
start_x = 1374
start_y = 464
width = 2744
height = 2744
bins = 1
type = "rgb24"
